name: deploy
on: workflow_dispatch
jobs:
  delpoy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: 'ssh-keyscan -H ${{ secrets.SSH_TARGET }} >> ~/.ssh/known_hosts'
      - run: 'rsync -avz --exclude .github --exclude .git --exclude deployment --exclude fake-data --delete ./ githubactions@${{ secrets.SSH_TARGET }}:${{ secrets.WEB_ROOT }}'
